name: java matrix file

on: [push]

jobs:
    run_java_matrix:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [8, 11, 17]

        steps:
            - name: copy files
              uses: actions/checkout@v3

            - name: install java
              uses: actions/setup-java@v3
              with:
                java-version: ${{matrix.java}}
                distribution: temurin
            
            - name: compile java
              run: javac Main.java
            
            - name: run java
              run: java Main


