name: run java

on: [push]

jobs:
    run_java:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: install java
              uses: actions/setup-java@v3
              with:
                java-version: 17
                distribution: temurin
            
            - name: Compile java
              run: javac Main.java
            
            - name: run java
              run: java Main

            
